allowing empty lines for instruction macros.
quilt/etk pull request #94
Opened 2022-04-12 20:50 UTC by Saw-mon-and-Natalie

According to the old pest grammar for instruction macros:

```pest
instruction_macro_definition = { 
    "%macro" ~ function_declaration ~ NEWLINE* ~ 
        (instruction_macro_stmt ~ NEWLINE)* ~ 
    "%end"
}
```

macros like the follwing are allowed:

```asm
%macro foo()
    
    
    push1 0
%end
```

we changed the grammar to allow empty lines after and in between `instruction_macro_stmt`'s. So that the following macros would also be well-defined:

```asm
%macro foo()
    
    
    push1 0

    chainid

%end
```

It would make the `.etk` code more readable.

Grammar change:

```diff
- ... (instruction_macro_stmt ~ NEWLINE)* ...
+ ... (instruction_macro_stmt ~ NEWLINE*)* ...
```

A test for this feature has also been added: `instruction_macro_with_empty_lines`

2022-04-13 12:45 UTC, lightclient requested changes
Hi @Saw-mon-and-Natalie, thank you for your PR! This is a good catch, it should be possible to have an arbitrary number of newlines between instructions. I think using `*` is problematic here though because `NEWLINE` is currently the delimiter for instructions. If it can be matched `0` times, then the following will assemble `600146`:

```asm
%macro foo()
    push1 0 chainid
%end
%foo
```

I think using `+` instead will resolve this. Would you mind updating that and adding a test to ensure the above example does not assemble?

2022-04-13 14:11 UTC, Saw-mon-and-Natalie commented
Hi @lightclient 

Great point. I'll change my PR.

2022-04-14 03:34 UTC, SamWilsn approved these changes

2022-04-14 13:09 UTC, lightclient approved these changes
LGTM

2022-04-14 13:10 UTC, merged